import i18n from './i18n';

export default {
    [i18n.AboutTitle]: 'Приветсвуем в getpass!',
    [i18n.AboutStepsTitle]: '\nКак взаимодействовать:',
    [i18n.AboutSteps]: `1. Выберите логин
        2. Выберите вебсайт
        3. Введите секретное слово
        4. Сгенерируйте пароль`,
    [i18n.AboutPlatformTitle]: '\nСписок платформ:',
    [i18n.AboutTipsTitle]: '\nДоп. информация:',
    [i18n.AboutTips]: `1. Ваше устройство локально хранит настройки, а также список логинов и вебсайтов.
        2. Секретное слово и сгенерированные пароли нигде не хранятся.
        3. Приложению не требуется доступ в интернет, поэтому ваши данные не покидают ваше устройство.
        4. Ознакомьтесь с разделом настроек для использования дополнительного функционала.`,
    [i18n.AboutAfterWord]: `\nБезопасного использования!
        @stellarbears, @git-kat`,
    [i18n.AboutBrowser]: 'Браузер\n',
    [i18n.AboutDesktop]: 'Настольный ПК\n',
    [i18n.AboutMobile]: 'Мобильный\n',
    [i18n.AboutWeb]: 'Сервис\n',
    [i18n.AboutTileTitle]: 'О проекте',
    [i18n.AccentColorTitle]: 'Цвет оттенка',
    [i18n.AddNewLoginPlaceholder]: 'andromeda',
    [i18n.AddNewLoginText]: 'Введите логин',
    [i18n.AddNewServicePlaceholder]: 'milkyway.com',
    [i18n.AddNewServiceText]: 'Введите веб-сайт',
    [i18n.AlreadyExistingLogin]: 'Логин уже добавлен',
    [i18n.AlreadyExistingService]: 'Веб-сайт уже добавлен',
    [i18n.AppTitle]: 'GetPass!',
    [i18n.AutoBrightness]: 'Автоматически менять тему',
    [i18n.BrightnessDark]: 'Темная',
    [i18n.BrightnessLight]: 'Светлая',
    [i18n.BrightnessTitle]: 'Тема',
    [i18n.Cancel]: 'Назад',
    [i18n.ChangeLanguageTitle]: 'Язык',
    [i18n.ClipboardExpirationTitle]: 'Время жизни буфера',
    [i18n.ColorTileTitle]: 'Персонализация',
    [i18n.Dismiss]: 'Понятно',
    [i18n.MigratePasswordsTitle]: 'Извлечь все пароли',
    [i18n.EditLoginAddFirst]: 'Нажмите кнопку ( + ), чтобы добавить Ваш первый логин',
    [i18n.EditLoginFilterPlaceholder]: '',
    [i18n.EditLoginTitle]: 'Логины',
    [i18n.EditServiceAddFirst]: 'Нажмите кнопку ( + ), чтобы добавить Ваш первый веб-сайт',
    [i18n.EditServiceFilterPlaceholder]: '',
    [i18n.EditServiceTitle]: 'Веб-сайты',
    [i18n.ExportDataTitle]: 'Экспорт Getpass!',
    [i18n.ExportKeyPlaceholder]: 'Ключ (опционально)',
    [i18n.FullyVisible]: 'полная',
    [i18n.GenerateButtonActive]: 'getpass!',
    [i18n.GenerateButtonSelectLogin]: 'Выберите логин',
    [i18n.GenerateButtonSelectService]: 'Выберите веб-сайт',
    [i18n.GenerateButtonUpdateSecret]: 'Обновите ключевое слово',
    [i18n.GenerationMockPageTitle]: 'Генерация пароля...',
    [i18n.ImportDataPlaceholder]: 'Экспортированные данные',
    [i18n.ImportErrorMessage]: 'Некорректный ключ или поврежденные данные',
    [i18n.ImportKeyPlaceholder]: 'Ключ (опционально)',
    [i18n.ImportDataTitle]: 'Импорт Getpass!',
    [i18n.Loading]: 'Ожидайте...',
    [i18n.LoginTileButton]: 'изменить',
    [i18n.LoginTileMock]: 'Выберете логин',
    [i18n.LoginTileTitle]: 'Логин',
    [i18n.LoginVisibilityEnding]: 'символ(ов) видно',
    [i18n.LoginVisibilityTitle]: 'Видимость логина',
    [i18n.MainTab]: 'Генератор',
    [i18n.MainTileTitle]: 'Безопасность',
    [i18n.ManagementTileTitle]: 'Управление данными',
    [i18n.Min]: 'мин.',
    [i18n.NotifyClipboardWiped]: 'Буфер обмена очищен',
    [i18n.NotifyExportSucceed]: 'Экспорт завершен',
    [i18n.NotifyIncompatibleParams]: 'Параметры ядра несовместимы с вашим устройством',
    [i18n.NotifyImportSucceed]: 'Импорт завершен',
    [i18n.NotifyPasswordGenerated]:
        'Пароль сгенерирован и скопирован в буфер обмена',
    [i18n.NotifyPasswordsMigrated]: 'Все пароли скопированы в буфер обмена',
    [i18n.OK]: 'Oк',
    [i18n.OptionCounter]: 'Счётчик',
    [i18n.OptionLowerCase]: 'a-z',
    [i18n.OptionNumbers]: 'Цифры',
    [i18n.OptionPassLength]: 'Длина',
    [i18n.OptionSpecialChars]: 'Символы',
    [i18n.OptionUpperCase]: 'A-Z',
    [i18n.PrimaryColorTitle]: 'Основной цвет',
    [i18n.ResetDataTitle]: 'Сбросить данные',
    [i18n.ResetDataPlaceholder]:
        'Вы уверены, что хотите безвозвратно удалить все данные?',
    [i18n.Sec]: 'сек.',
    [i18n.SecretTileButton]: 'обновить',
    [i18n.SecretTileMock]: 'Неактивно',
    [i18n.SecretTileTitle]: 'Секретное слово',
    [i18n.SecretTimeLeft]: 'сек. осталось',
    [i18n.SecretTimerTitle]: 'Время жизни секрета',
    [i18n.ServiceTileButton]: 'изменить',
    [i18n.ServiceTileMock]: 'Выберете веб-сайт',
    [i18n.ServiceTileTitle]: 'Веб-сайт',
    [i18n.ServiceVisibilityEnding]: 'символ(ов) видно',
    [i18n.ServiceVisibilityTitle]: 'Сокрытие Сервисов',
    [i18n.SettingsTab]: 'настройки',
    [i18n.ScryptDefault]: 'По-умолчанию',
    [i18n.ScryptTough]: 'Нелегальный',
    [i18n.ScryptTileTitle]: 'Настройка ядра',
    [i18n.ScryptCostFactor]: 'Сложность вычисления',
    [i18n.ScryptBlockSizeFactor]: 'Размер блока',
    [i18n.ScryptWarning]:
        'Предупреждение: Вы должны быть уверены в совершаемых вами изменениях. Это напрямую влияет на время генерации паролей, а так же на сам результат. Более того, помимо секрета вам необходимо будет помнить использованные здесь настройки в том случае, если вы их меняли, для того, чтобы на разных устройствах получать одни и те же пароли. Вы всегда можете вернуться к настройкам по умолчанию.',
    [i18n.Update]: 'Обновить',
    [i18n.VisualHash]: 'Визуализация секрета',
    [i18n.UpdateSecretText]: 'Секретное слово',
    [i18n.WipeClipboardTitle]: 'Очистить буфер обмена',
};
